resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/cah-johnkeyes/concourse-demo-app.git
      branch: master
  - name: deploy-config
    type: git
    source:
      uri: https://github.com/cah-johnkeyes/concourse-demo-app-deploy.git
      branch: master

jobs:
  - name: unit-test
    plan:
      - get: source-code
        trigger: true
      - task: run-tests
        priviledged: true
        file: source-code/ci/tasks/unit-test.yml
  - name: publish
    plan:
      - get: source-code
        passed: [unit-test]
        trigger: true
      - task: publish
        priviledged: true
        file: source-code/ci/tasks/assemble-publish.yml
  - name: deploy
    plan:
      - get: source-code
      - get: deploy-config
        trigger: true
      - task: deploy-app
        priviledged: true
        file: source-code/ci/tasks/deploy.yml