platform: linux

image_resource:
    type: docker-image
    source:
        repository: java
        tag: latest

inputs:
  - name: deploy-config
    path: config

run:
    path: "echo"
    args: ["DEPLOYMENT"]

params:
    TERM: -dumb
    GRADLE_OPTS: -Dorg.gradle.native=false
