platform: linux

image_resource:
    type: docker-image
    source:
        repository: frekele/gradle
        tag: 3.0-jdk8

inputs:
  - name: source-code
    path: app

outputs:
  - name: published-artifacts

# run:
#     path: "gradle"
#     args: ["--build-file", "app/build.gradle", "assemble", "publish", "-PrepoUrl=$REPO_URL", "-PrepoUsername=$REPO_USERNAME", "-PrepoPassword=$REPO_PASSWORD"]
run:
    path: sh
    args: ["app", "published-artifacts"]

params:
    TERM: -dumb
    GRADLE_OPTS: -Dorg.gradle.native=false
