platform: linux

image_resource:
    type: docker-image
    source:
        repository: frekele/gradle
        tag: 3.0-jdk8

inputs:
  - name: pipeline
  - name: source-code

outputs:
  - name: published-artifacts

run:
    path: "pipeline/tasks/publish.sh"
    args: ["source-code", "published-artifacts"]

params:
    TERM: -dumb
    GRADLE_OPTS: -Dorg.gradle.native=false
