platform: linux

image_resource:
    type: docker-image
    source:
        repository: frekele/gradle
        tag: 3.0-jdk8

inputs:
  - name: source-code
    path: app

run:
    path: "gradle"
    args: ["--build-file", "app/build.gradle", "test"]

params:
    TERM: -dumb
    GRADLE_OPTS: -Dorg.gradle.native=false
