platform: linux

image_resource:
    type: docker-image
    source:
        repository: java
        tag: latest

inputs:
  - name: deploy-config
  - name: published-artifacts

run:
    path: "cp"
    args: ["published-artifacts/VERSION", "deploy-config/VERSION_TO_DEPLOY"]

params:
    TERM: -dumb
