platform: linux

image_resource:
    type: docker-image
    source:
        repository: java
        tag: latest

inputs:
  - name: deploy-config
  - name: published-artifacts

outputs:
    - name: put

run:
    path: "cp"
    args: ["published-artifacts/VERSION", "put/VERSION_TO_DEPLOY"]

params:
    TERM: -dumb
